apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: thanos-querier-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: thanos-querier
  namespace: thanos
roleRef:
  kind: ClusterRole
  name: thanos-querier-cluster-role
  apiGroup: rbac.authorization.k8s.io

