apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: thanos-querier
      containers:
      - name: thanos-querier
        image: quay.io/thanos/thanos:v0.39.0
        args:
        - "query"
        - "--http-address=0.0.0.0:9090"
        - "--query.auto-downsampling" #required to show downsampled data in grafana
        - "--endpoint=dnssrv+_grpc._tcp.prom.monitoring.svc.cluster.local:19090"
        - "--endpoint=dnssrv+_grpc._tcp.thanos-store-gateway.thanos.svc.cluster.local:19090"
        ports:
        - containerPort: 9090
