apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thanos

resources:
  - deployment.yaml
  - service.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - service-account.yaml

commonLabels:
  app: thanos-querier

