---
apiVersion: v1
kind: Service
metadata:
  name: flexget-service
spec:
  type: NodePort
  ports:
    - name: flexget-http
      port: 5050
      protocol: TCP
      nodePort: 30002
      targetPort: flexget-http
  sessionAffinity: None

