apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway
spec:
  ports:
    - name: grpc
      port: 19090
      targetPort: 19090
    - name: http
      port: 19191
      targetPort: 19191
