apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefox02
spec:
  project: default
  source:
    repoURL: 'git@github.com:Kapujino/k8s.git'
    path: services/base/firefox02
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
  - group: "apps"
    kind: "Deployment"
    jsonPointers:
    - /spec/replicas
  syncPolicy:
    automated: {}
