apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flexget
spec:
  project: default
  source:
    repoURL: 'git@github.com:Kapujino/k8s.git'
    path: services/base/flexget
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
#  syncPolicy:
#    automated: {}
