apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - monitoring.yaml
  - flexget.yaml
  - adguard.yaml
  - bookmarks.yaml
  - deconz.yaml
  - dl.yaml
  - fenrus.yaml
  - firefox.yaml
  - homeassistant.yaml
  - ldap.yaml
  - nextcloud.yaml
  - ombi.yaml
  - plex.yaml
  - tautulli.yaml
  - teamspeak.yaml
  - tdarr.yaml

commonLabels:
  app.kubernetes.io/app-type: services
