apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - monitoring.yaml
  - adguard.yaml
  - bookmarks.yaml
  - jd01.yaml
  - firefox.yaml
  - homeassistant.yaml
  - ldap.yaml
  - nextcloud.yaml
  - plex.yaml
  - tautulli.yaml
  - teamspeak6.yaml
  - tsbanner.yaml


commonLabels:
  app.kubernetes.io/app-type: services
