---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  template:
    metadata:
      annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/port:   '9100'
    spec:
      hostNetwork:  true
      containers:
      - args:
        - --path.sysfs=/host/sys
        - --path.rootfs=/host/root
        - --no-collector.wifi
        - --no-collector.hwmon
        - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+|run/containerd.+|etc/.+)($|/)
        - --collector.netdev.device-exclude=^(veth.*|cali.*)$
        - --collector.systemd
        - --collector.processes
        name: node-exporter
        image: prom/node-exporter:v1.7.0
        ports:
          - containerPort: 9100
            protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 180Mi
          requests:
            cpu: 102m
            memory: 180Mi
        volumeMounts:
        - mountPath: /host/sys
          mountPropagation: HostToContainer
          name: sys
          readOnly: true
        - mountPath: /host/root
          mountPropagation: HostToContainer
          name: root
          readOnly: true
#        - mountPath: /etc/hostname
#          mountPropagation: HostToContainer
#          name: hostname
#          readOnly: true
#        env:
#        - name: HOSTNAME
#          valueFrom:
#            fieldRef:
#              fieldPath: spec.nodeName
      volumes:
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /
        name: root
#      - hostPath:
#          path: /etc/hostname
#        name: hostname

