apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - daemonset.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/component: exporter
  app.kubernetes.io/name: node-exporter
