---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

#https://metallb.universe.tf/installation/
resources:
  - github.com/metallb/metallb/config/native?ref=v0.15.2
  - metallb_ip_range.yaml

