---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: adguard
          image: adguard/adguardhome
          ports:
          - containerPort: 53
            name: adguard-dns-tcp
            protocol: TCP
          - containerPort: 53
            name: adguard-dns-udp
            protocol: UDP
          - containerPort: 80
            name: adguard-http
            protocol: TCP
          - containerPort: 443
            name: adguard-https
            protocol: TCP
          - containerPort: 3000
            name: adguard-web
            protocol: TCP
          envFrom:
            - configMapRef:
                name: default-env
          volumeMounts:
          - mountPath: /opt/adguardhome/conf
            name: adguard-conf-volume
          - mountPath: /opt/adguardhome/work
            name: adguard-data-volume
      dnsPolicy: ClusterFirst
      volumes:
      - name: adguard-conf-volume
        nfs:
          server: 192.168.1.200
          path: /volume1/nfs/dockerfiles/volumes/adguard/config
          readOnly: false
      - name: adguard-data-volume
        nfs:
          server: 192.168.1.200
          path: /volume1/nfs/dockerfiles/volumes/adguard/data
          readOnly: false
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
              weight: 100

