---
apiVersion: v1
kind: Service
metadata:
  name: firefox-service
spec:
  type: NodePort
  ports:
    - name: firefox-tcp
      port: 5900
      protocol: TCP
      targetPort: firefox-tcp
      nodePort: 30000
    - name: firefox-udp
      port: 5900
      protocol: UDP
      nodePort: 30000
      targetPort: firefox-udp
  sessionAffinity: None

