apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Kapujino/k8s
    targetRevision: HEAD
    path: apps/services
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
