apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.1.5/manifests/install.yaml
  - apps-infra.yaml
  - apps-services.yaml

patchesJson6902:
- target:
    version: v1
    kind: Service
    name: argocd-server-metrics
  path: service-metrics.yaml
- target:
    version: v1
    kind: Service
    name: argocd-metrics
  path: service.yaml

commonLabels:
  app: argocd

