---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-https
spec:
  type: ClusterIP
  ports:
    - name: nextcloud-https
      port: 443
      protocol: TCP
      targetPort: nextcloud-https
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-db
spec:
  type: ClusterIP
  ports:
    - name: nextcloud-db
      port: 3306
      protocol: TCP
      targetPort: nextcloud-db
  sessionAffinity: None
#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: ldap
##  namespace: nextcloud
#spec:
#  type: ExternalName
#  externalName: ldap.default.svc.cluster.local

