---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      hostNetwork:  true
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:2024.2.2
          ports:
          - containerPort: 8123
            name: homeassistant
            protocol: TCP
          envFrom:
            - configMapRef:
                name: default-env-internal
          volumeMounts:
          - mountPath: /config/
            name: homeassistant-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - zbox
      dnsPolicy: ClusterFirst
      volumes:
      - name: homeassistant-volume
        nfs:
          server: 192.168.1.200
          path: /volume1/nfs/dockerfiles/volumes/homeassistant/
          type: Directory

