---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  ports:
    - name: homeassistant
      port: 8123
      protocol: TCP
      targetPort: homeassistant
  sessionAffinity: None

