---
apiVersion: v1
kind: Service
metadata:
  name: prom
spec:
  type: ClusterIP
  ports:
    - name: prom-http
      port: 9090
      protocol: TCP
      targetPort: prom-http
#thanos
    - name: grpc
      port: 19090
      targetPort: 19090
    - name: http
      port: 19191
      targetPort: 19191
#  externalTrafficPolicy: Local # only with external types

