apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Kapujino/k8s.git'
    path: infra/base/argocd
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
  - group: ""
    kind: "Secret"
    name: "argocd-secret"
    namespace: "argocd"
    jsonPointers:
    - /data
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - Prune=false
    automated: {}
