apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
spec:
  project: default
  source:
    repoURL: 'git@github.com:Kapujino/k8s.git'
    path: infra/base/calico
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
  syncPolicy:
    automated: {}
