apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: default
  source:
    repoURL: 'git@github.com:Kapujino/k8s.git'
    path: infra/base/ingress-nginx
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
#  ignoreDifferences:
#  - group: "batch"
#    kind: "Job"
#    name: "ingress-nginx-admission-*"
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    automated: {}
