apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - calico.yaml
  - ingress-nginx.yaml
  - metallb.yaml
  - argocd.yaml

commonLabels:
  app.kubernetes.io/app-type: infra
