apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfs-provisioner

resources:
  - namespace.yaml
  - github.com/kubernetes-sigs/nfs-subdir-external-provisioner/deploy

patchesStrategicMerge:
  - patch_nfs.yaml
