---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/projectcalico/calico/v3.30.2/manifests/calico.yaml

patches:
- target:
    kind: DaemonSet
    name: calico-node
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: CALICO_IPV4POOL_CIDR
        value: "10.64.0.0/16"
