apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: ldap

configMapGenerator:
 - name: ldap-env
   envs:
   - default.env
   - ldap.env
 - name: ldap-web-env
   envs:
   - default.env
   - ldap-web.env
