apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - pvc.yaml
  - pv.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: grafana

#configMapGenerator:
#  - name: default-env
#    envs:
#    - default.env

