---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
#  mountOptions:
#    - nfsvers=3
  nfs:
    server: 192.168.1.200
    path: /volume1/nfs/dockerfiles/volumes/monitoring/grafana

