---
apiVersion: v1
kind: Service
metadata:
  name: tdarr
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.230
spec:
  type: LoadBalancer
  ports:
    - name: tdarr-ui
      port: 8265
      protocol: TCP
      targetPort: tdarr-ui
    - name: tdarr-server
      port: 8266
      protocol: TCP
      targetPort: tdarr-server
  sessionAffinity: None
  externalTrafficPolicy: Local
