apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmarks
  labels:
    app: bookmarks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmarks
  template:
    metadata:
      labels:
        app: bookmarks
    spec:
      containers:
      - name: bookmarks
        image: nginx:1.29.3
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: html-volume
        configMap:
          name: bookmarks-configmap

