---
apiVersion: v1
kind: Service
metadata:
  name: dl-service
spec:
  type: NodePort
  ports:
    - name: jd-tcp
      port: 5900
      protocol: TCP
      nodePort: 30001
      targetPort: jd-tcp
    - name: jd-udp
      port: 5900
      protocol: UDP
      nodePort: 30001
      targetPort: jd-udp
    - name: jd-direct-tcp
      port: 30050
      protocol: TCP
      targetPort: jd-direct-tcp
      nodePort: 30050
  sessionAffinity: None

