---
#apiVersion: v1
#kind: Service
#metadata:
#  name: plex-udp
#  labels:
#    app: plex
#spec:
#  type: NodePort
#  ports:
#    - name: dnla-udp
#      port: 1900
#      protocol: UDP
#      targetPort: dnla-udp
#      nodePort: 1900
#    - name: gdm32410
#      port: 32410
#      protocol: UDP
#      targetPort: 32410
#      nodePort: 32410
#    - name: gdm32412
#      port: 32412
#      protocol: UDP
#      targetPort: 32412
#      nodePort: 32412
#    - name: gdm32413
#      port: 32413
#      protocol: UDP
#      targetPort: 32413
#      nodePort: 32413
#    - name: gdm32414
#      port: 32414
#      protocol: UDP
#      targetPort: 32414
#      nodePort: 32414
#  selector:
#    app: plex
#  sessionAffinity: None
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: plex-tcp
#  labels:
#    app: plex
#spec:
#  type: NodePort
#  ports:
#    - name: pms
#      port: 32400
#      protocol: TCP
#      targetPort: pms
#      nodePort: 32400
#    - name: home-theatre
#      port: 3005
#      protocol: TCP
#      targetPort: home-theatre
#      nodePort: 3005
#    - name: discovery
#      port: 5353
#      protocol: TCP
#      targetPort: discovery
#      nodePort: 5353
#    - name: roku
#      port: 8324
#      protocol: TCP
#      targetPort: roku
#      nodePort: 8324
#    - name: dnla-tcp
#      port: 32469
#      protocol: TCP
#      targetPort: dnla-tcp
#      nodePort: 32469
#  selector:
#    app: plex
#  sessionAffinity: None

