### MetalLB will always use this IP for the ingress nginx loadbalances service
- op: replace
  path: /spec/type
  value: LoadBalancer
- op: add
  path: /metadata/annotations/metallb.universe.tf~1ip-allocated-from-pool
  value: default-pool
- op: add
  path: /metadata/annotations/metallb.universe.tf~1loadBalancerIPs
  value: 192.168.1.210
