---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamspeak
spec:
  replicas: 0
  strategy:
    type: Recreate
  template:
    spec:
      hostNetwork:  true
      containers:
        - name: teamspeak
          image: teamspeak:3.13.7
          envFrom:
            - configMapRef:
                name: teamspeak-env
          volumeMounts:
          - mountPath: /var/ts3server/
            name: teamspeak-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - zbox
      dnsPolicy: ClusterFirst
      volumes:
      - name: teamspeak-volume
        nfs:
          server: 192.168.1.10
          path: /mnt/volumes/nfs/teamspeak/server
          readOnly: false
